//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YodaIpsum.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YodaIpsum.Shared.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oohhh.
        ///Jedi Master.
        ///Yoda.
        ///You seek Yoda.
        ///Mmm.
        ///Take you to him, I will.
        ///Yes, yes.
        ///But now, we must eat.
        ///Come.
        ///Good food.
        ///Come.
        ///Patience! For the Jedi it is time to eat as well.
        ///Eat, eat.
        ///Hot.
        ///Good food, hm?
        ///Good, hmm?
        ///Not far.
        ///Yoda not far.
        ///Patience.
        ///Soon you will be with him.
        ///Rootleaf, I cook.
        ///Why wish you become Jedi?
        ///Hm?
        ///Ah, your father.
        ///Powerful Jedi was he, powerful Jedi, mmm.
        ///I cannot teach him.
        ///The boy has no patience.
        ///Hmmm.
        ///Much anger in him, like his father.
        ///Hah.
        ///He is  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CoreText {
            get {
                return ResourceManager.GetString("CoreText", resourceCulture);
            }
        }
    }
}
